### PR TITLE
Update dependency for Fluent 1.0

### PR DESCRIPTION
**Pull request by harlanhaskins**

### CODE REVIEW

**Comment by adriencanterot** [comment]
Hey @harlanhaskins, thanks for the interest ! I made a few changes myself to fully pass to swift 3 (ci and testing stuff), however before reaching 1.0 there needs to be an update to vapor/csqlite and vapor/sqlite packages [#9 from sqlite](https://github.com/vapor/sqlite/pull/9)

**Comment by harlanhaskins** [comment]
How's this effort doing? Are we close to getting this updated?

**Comment by tanner0101** [comment]
SQLite 1.0 has been pushed, so we should be good to update this: https://github.com/vapor/sqlite/releases

**Comment by adriencanterot** [comment]
Okay, ready to be pushed to 1.0 ! @tannernelson

**Comment by tanner0101** [comment]
Nice work guys :D

**Pull request merged**
