### PR TITLE
Fluent 0.11 ready

### PR DESCRIPTION
**Pull request by adriencanterot**
Hi everyone,
This update is mostly about updating to the new Vapor and 09-06 and getting SQLite back on track !
## New :
- Joined queries
- LICENSE
- Tests
## Updated :
- .swift-version to 09-06
- improved code
- Fluent 0.11

I thought I'd create a PR since I was starting to write a lot of code on my own.
Plus, I wanted to include people in the review/update process of sqlite so when the times Vapor 1.0 comes out, there wouldn't be much work left to do with sqlite.
Thank you very much for giving attention to this !

### CODE REVIEW

**Comment by tanner0101** [comment]
This is looking good! We just need to get the sqlite package updated now :P

**Comment by adriencanterot** [comment]
Alright, joined queries now work ! I also added test from the mysql driver.

**Comment by tanner0101** [comment]
Looks like a syntax error with `try statement.null()`

**Comment by adriencanterot** [comment]
Oh I know, it comes from [that PR](https://github.com/vapor/sqlite/pull/6) but hasn't gotten an update yet. No need to hurry though, you guys have a lot of work to do regarding more important issues !

**Comment by adriencanterot** [comment]
Hi @tanner , this one is ready to be pulled and tagged 
Added gold master and fluent 0.11 support as well
Thanks !

**Comment by tanner0101** [comment]
Awesome! Great work on this.

**Pull request merged**
